mod config;
mod events;
mod scheduler;
mod secret_manager;
mod server;
mod transactions;
mod utils;

use std::collections::HashMap;
use std::sync::Arc;

use actix_web::web::Data;
use actix_web::{App, HttpServer};
use alloy::primitives::Address;
use alloy::signers::k256::ecdsa::SigningKey;
use alloy::signers::utils::public_key_to_address;
use anyhow::{Context, Result};
use clap::Parser;
use tokio::fs;

use server::*;
use tokio::sync::RwLock;
use utils::{verify_rpc_url, AppState, ConfigManager};

// SECRET STORE CONFIGURATION PARAMETERS
#[derive(Parser, Debug)]
#[command(author, version, about, long_about = None)]
struct Cli {
    // Server port
    #[clap(long, value_parser, default_value = "6002")]
    port: u16,

    // Path to the configuration file
    #[clap(
        long,
        value_parser,
        default_value = "./oyster_secret_store_config.json"
    )]
    config_file: String,
}

#[tokio::main]
async fn main() -> Result<()> {
    let args = Cli::parse();
    let config_manager = ConfigManager::new(&args.config_file);
    let config = config_manager.load_config().unwrap();

    verify_rpc_url(&config.http_rpc_url).context("Invalid RPC URL")?;

    // Read the 'secp256k1' private key of the enclave instance generated by keygen
    let enclave_signer_key = SigningKey::from_slice(
        fs::read(config.enclave_signer_file)
            .await
            .context("Failed to read the enclave signer key")?
            .as_slice(),
    )
    .context("Invalid enclave signer key")?;

    let enclave_address = public_key_to_address(&enclave_signer_key.verifying_key());
    println!("Enclave address {:?}", enclave_address);

    // Initialize App data that will be shared across multiple threads and tasks
    let app_data = Data::new(AppState {
        secret_store_path: config.secret_store_path,
        common_chain_id: config.common_chain_id,
        http_rpc_url: config.http_rpc_url,
        web_socket_url: config.web_socket_url,
        secret_store_contract_addr: config.secret_store_contract_addr,
        secret_manager_contract_addr: config.secret_manager_contract_addr,
        num_selected_stores: config.num_selected_stores,
        enclave_address: enclave_address,
        enclave_signer: enclave_signer_key,
        immutable_params_injected: false.into(),
        mutable_params_injected: false.into(),
        enclave_owner: Address::ZERO.into(),
        gas_wallet: Arc::new(RwLock::new(String::new())),
        http_rpc_txn_manager: None.into(),
        enclave_registered: false.into(),
        events_listener_active: false.into(),
        last_block_seen: 0.into(),
        acknowledgement_timeout: config.acknowledgement_timeout,
        mark_alive_timeout: config.mark_alive_timeout,
        secrets_awaiting_acknowledgement: HashMap::new().into(),
        secrets_created: HashMap::new().into(),
        secrets_stored: HashMap::new().into(),
    });

    // Start actix server to expose the secret store API endpoints outside the enclave
    let server = HttpServer::new(move || {
        App::new()
            .app_data(app_data.clone())
            .service(index)
            .service(inject_immutable_config)
            .service(inject_mutable_config)
            .service(get_secret_store_details)
            .service(export_signed_registration_message)
            .service(inject_and_store_secret)
    })
    .bind(("0.0.0.0", args.port))
    .context(format!("could not bind to port {}", args.port))?
    .run();

    println!("Node server started on port {}", args.port);

    server.await?;

    Ok(())
}
